// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Yume’s Spellbook",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Yume’s Spellbook",
            targets: ["AppModule"],
            bundleIdentifier: "com.LarissaOkabayashi.YumeSpellbook",
            teamIdentifier: "QS932KTLCZ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("media")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
